<<<<<<< HEAD
# Generated by Django 4.2.11 on 2025-03-10 17:06
=======
# Generated by Django 3.2.20 on 2025-03-10 16:56
>>>>>>> fef538d6894bd566436672cbde6e771f2dc0f98f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20241119_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
