# Generated by Django 4.2.11 on 2025-03-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]