<<<<<<< HEAD
# Generated by Django 4.2.11 on 2025-03-12 20:23

from django.db import migrations
=======
<<<<<<<< HEAD:Profile/migrations/0003_profile_avatar.py


========
>>>>>>>> scolopendra:Profile/migrations/0004_remove_profile_avatar.py
from django.db import migrations, models
>>>>>>> scolopendra


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Profile', '0003_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
=======
        ('Profile', '0002_auto_20241119_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
>>>>>>> scolopendra
