# Generated by Django 3.2.20 on 2025-03-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
