# Generated by Django 3.2.25 on 2024-11-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0002_auto_20241119_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
                ('students', models.ManyToManyField(null=True, to='Profile.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.teacher')),
            ],
        ),
    ]
