# Generated by Django 3.2.25 on 2024-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20241119_2227'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(to='Profile.Student'),
        ),
    ]
