# Generated by Django 3.2.25 on 2024-11-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20241119_2227'),
        ('Courses', '0002_alter_courses_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.student'),
        ),
    ]
