# Generated by Django 3.2.25 on 2024-11-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20241119_2227'),
        ('Courses', '0003_auto_20241119_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.CreateModel(
            name='StudentCourser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.courses')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.student')),
            ],
            options={
                'unique_together': {('courses', 'student')},
            },
        ),
    ]
