# Generated by Django 4.2.11 on 2025-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20241119_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
