# Generated by Django 4.2.11 on 2025-05-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profile_avatar'),
        ('Courses', '0007_completedtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtask',
            options={'verbose_name': 'Выполненное задание', 'verbose_name_plural': 'Выполненные задания'},
        ),
        migrations.AddField(
            model_name='completedtask',
            name='code_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.courses'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.student'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
